---
title: "Técnicas de Reamostragem"
output:
  html_document:
    df_print: paged
date: ''
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning = FALSE)
```

## Métodos de Downsample

```{r,echo=FALSE,warning=FALSE,message=FALSE}
library(tidymodels)
library(janitor)
library(stringr)
library(vip)
library(probably)
library(gt)
library(ggplot2)
library(patchwork)
library(themis)
library(recipes)
library(modeldata)

dados <- readRDS("dados_newtest.rds")

data <- dados  %>% 
  filter(as.Date(DT_SIN_PRI,format="%d/%m/%Y") < as.Date("01-12-2021",format="%d-%m-%Y")) %>% # 37.847 points
  mutate(classi_fin = as.factor(case_when(
    CLASSI_FIN == 1 ~ "não-covid",
    CLASSI_FIN == 2 ~ "não-covid",
    CLASSI_FIN == 3 ~ "não-covid",
    CLASSI_FIN == 5 ~ "covid-19",
    TRUE ~ NA_character_))
  ) %>% 
  filter(!is.na(classi_fin)) %>% 
  mutate(dt_notific = as.Date(DT_NOTIFIC, format = "%d/%m/%Y"),
         dt_sint = as.Date(DT_SIN_PRI, format = "%d/%m/%Y"),
         dt_interna = as.Date(DT_INTERNA, format = "%d/%m/%Y"),
         dt_pcr = as.Date(DT_PCR, format = "%d/%m/%Y"),
         dt_entuti  = as.Date(DT_ENTUTI,  format = "%d/%m/%Y"),
         dt_saiduti = as.Date(DT_SAIDUTI, format = "%d/%m/%Y"),
         dt_evoluca = as.Date(DT_EVOLUCA, format = "%d/%m/%Y"),
         dt_encerra = as.Date(DT_ENCERRA, format = "%d/%m/%Y"),
         dt_digita = as.Date(DT_DIGITA, format = "%d/%m/%Y")
  ) %>% 
  mutate(
    tempo_sintomas_hosp = as.numeric(dt_interna - dt_sint),
    tempo_sintomas_notific = as.numeric(dt_notific - dt_sint),
    tempo_uti = as.numeric(dt_saiduti - dt_entuti),
    tempo_sint_evolucao = as.numeric(dt_evoluca - dt_sint)
  ) %>% 
  select(idade,tempo_sintomas_notific,classi_fin) %>% 
  drop_na()

```

### DownSample

```{r,echo=TRUE}

# objeto <- data %>% select(diarreia2,saturacao2)
# 
# matrix <- distance(objeto)


# ds_rec <- recipe(classi_fin ~ idade + tempo_sintomas_notific, data = data) %>%
#   step_downsample(classi_fin) %>%
#   prep()
#     
# new_data <- juice(data,ds_rec)


g1 <- ggplot(data, aes(idade, tempo_sintomas_notific, color = classi_fin)) +
  geom_point(alpha=0.5) +
  labs(title = "Without downsample")


g2 <- recipe(classi_fin ~ idade + tempo_sintomas_notific, data = data) %>%
  step_downsample(classi_fin) %>%
  prep() %>%
  bake(new_data = NULL) %>%
  ggplot(aes(idade, tempo_sintomas_notific, color = classi_fin)) +
  geom_point(alpha=0.5) +
  labs(title = "With downsample")

g1
g2
```

```{r,echo=FALSE,eval=FALSE}
data(hpc_data)

hpc_data0 <- hpc_data %>%
  select(-protocol, -day)

orig <- count(hpc_data0, class, name = "orig")
# orig
#> # A tibble: 4 × 2
#>   class  orig
#>   <fct> <int>
#> 1 VF     2211
#> 2 F      1347
#> 3 M       514
#> 4 L       259

up_rec <- recipe(class ~ ., data = hpc_data0) %>%
  # Bring the majority levels down to about 1000 each
  # 1000/259 is approx 3.862
  step_downsample(class, under_ratio = 3.862) %>%
  prep()

training <- up_rec %>%
  bake(new_data = NULL) %>%
  count(class, name = "training")
# training
#> # A tibble: 4 × 2
#>   class training
#>   <fct>    <int>
#> 1 VF        1000
#> 2 F         1000
#> 3 M          514
#> 4 L          259

# Since `skip` defaults to TRUE, baking the step has no effect
baked <- up_rec %>%
  bake(new_data = hpc_data0) %>%
  count(class, name = "baked")
# baked
#> # A tibble: 4 × 2
#>   class baked
#>   <fct> <int>
#> 1 VF     2211
#> 2 F      1347
#> 3 M       514
#> 4 L       259

# Note that if the original data contained more rows than the
# target n (= ratio * majority_n), the data are left alone:
# orig %>%
#   left_join(training, by = "class") %>%
#   left_join(baked, by = "class")
#> # A tibble: 4 × 4
#>   class  orig training baked
#>   <fct> <int>    <int> <int>
#> 1 VF     2211     1000  2211
#> 2 F      1347     1000  1347
#> 3 M       514      514   514
#> 4 L       259      259   259



g1 <- ggplot(circle_example, aes(x, y, color = class)) +
  geom_point() +
  labs(title = "Without downsample")

g2 <- recipe(class ~ x + y, data = circle_example) %>%
  step_downsample(class) %>%
  prep() %>%
  bake(new_data = NULL) %>%
  ggplot(aes(x, y, color = class)) +
  geom_point() +
  labs(title = "With downsample")

g1
g2
```

#### Métricas modelo XGboost

```{r}
readRDS("metricas_downsample.rds")
```


### NearMiss

```{r,echo=FALSE}
g1 <- ggplot(data, aes(idade, tempo_sintomas_notific, color = classi_fin)) +
  geom_point(alpha=0.5) +
  labs(title = "Without Nearmiss")


g2 <- recipe(classi_fin ~ idade + tempo_sintomas_notific, data = data) %>%
  step_nearmiss(classi_fin) %>%
  prep() %>%
  bake(new_data = NULL) %>%
  ggplot(aes(idade, tempo_sintomas_notific, color = classi_fin)) +
  geom_point(alpha=0.5) +
  labs(title = "With Nearmiss")

g1
g2
```

#### Métricas modelo XGboost

```{r}
readRDS("metricas_nearmiss.rds")
```


### Links de Tomek

```{r}
g1 <- ggplot(data, aes(idade, tempo_sintomas_notific, color = classi_fin)) +
  geom_point(alpha=0.5) +
  labs(title = "Without Tomek")


g2 <- recipe(classi_fin ~ idade + tempo_sintomas_notific, data = data) %>%
  step_tomek(classi_fin) %>%
  prep() %>%
  bake(new_data = NULL) %>%
  ggplot(aes(idade, tempo_sintomas_notific, color = classi_fin)) +
  geom_point(alpha=0.5) +
  labs(title = "With Tomek")

g1
g2
```

#### Métricas modelo XGboost

```{r}
readRDS("metricas_tomek.rds")
```

## Métodos de Up-Sample

### Upsample

```{r,echo=FALSE}
g1 <- ggplot(data, aes(idade, tempo_sintomas_notific, color = classi_fin)) +
  geom_point(alpha=0.5) +
  labs(title = "Without Up-Sample")


g2 <- recipe(classi_fin ~ idade + tempo_sintomas_notific, data = data) %>%
  step_upsample(classi_fin) %>%
  prep() %>%
  bake(new_data = NULL) %>%
  ggplot(aes(idade, tempo_sintomas_notific, color = classi_fin)) +
  geom_point(alpha=0.5) +
  labs(title = "With Up-Sample")

g1
g2
```

#### Métricas modelo XGboost

```{r}
readRDS("metricas_upsample.rds")
```

### Smote

```{r,echo=FALSE}
g1 <- ggplot(data, aes(idade, tempo_sintomas_notific, color = classi_fin)) +
  geom_point(alpha=0.5) +
  labs(title = "Without Smote")


g2 <- recipe(classi_fin ~ idade + tempo_sintomas_notific, data = data) %>%
  step_smote(classi_fin) %>%
  prep() %>%
  bake(new_data = NULL) %>%
  ggplot(aes(idade, tempo_sintomas_notific, color = classi_fin)) +
  geom_point(alpha=0.5) +
  labs(title = "With Smote")

g1
g2
```

#### Métricas modelo XGboost

```{r}
readRDS("metricas_smote.rds")
```

### SMOTE NC 

#### Métricas modelo XGboost

```{r}
readRDS("metricas_smoteNC.rds")
```

### ADASYN 

```{r}
g1 <- ggplot(data, aes(idade, tempo_sintomas_notific, color = classi_fin)) +
  geom_point(alpha=0.5) +
  labs(title = "Without Adasyn")


g2 <- recipe(classi_fin ~ idade + tempo_sintomas_notific, data = data) %>%
  step_adasyn(classi_fin) %>%
  prep() %>%
  bake(new_data = NULL) %>%
  ggplot(aes(idade, tempo_sintomas_notific, color = classi_fin)) +
  geom_point(alpha=0.5) +
  labs(title = "With Adasyn")

g1
g2
```

#### Métricas modelo XGboost

```{r}
readRDS("metricas_adasyn.rds")
```

### Borderline Smote

```{r}
g1 <- ggplot(data, aes(idade, tempo_sintomas_notific, color = classi_fin)) +
  geom_point(alpha=0.5) +
  labs(title = "Without Boderline-SMOTE")


g2 <- recipe(classi_fin ~ idade + tempo_sintomas_notific, data = data) %>%
  step_bsmote(classi_fin,all_neighbors = FALSE) %>%
  prep() %>%
  bake(new_data = NULL) %>%
  ggplot(aes(idade, tempo_sintomas_notific, color = classi_fin)) +
  geom_point(alpha=0.5) +
  labs(title = "With  borderline-SMOTE, all_neighbors = FALSE")

g3 <- recipe(classi_fin ~ idade + tempo_sintomas_notific, data = data) %>%
  step_bsmote(classi_fin,all_neighbors = TRUE) %>%
  prep() %>%
  bake(new_data = NULL) %>%
  ggplot(aes(idade, tempo_sintomas_notific, color = classi_fin)) +
  geom_point(alpha=0.5) +
  labs(title = "With  borderline-SMOTE, all_neighbors = TRUE")

g1
g2
g3
```

#### Métricas modelo XGboost

##### Method 1

```{r}
readRDS("metricas_bsmotef.rds")
```

##### Method 2

```{r}
readRDS("metricas_bsmotet.rds")
```

### ROSE 

```{r}
g1 <- ggplot(data, aes(idade, tempo_sintomas_notific, color = classi_fin)) +
  geom_point(alpha=0.5) +
  labs(title = "Without ROSE")


g2 <- recipe(classi_fin ~ idade + tempo_sintomas_notific, data = data) %>%
  step_rose(classi_fin) %>%
  prep() %>%
  bake(new_data = NULL) %>%
  ggplot(aes(idade, tempo_sintomas_notific, color = classi_fin)) +
  geom_point(alpha=0.5) +
  labs(title = "With  ROSE")

g1
g2
```

